%%  interface control
H.scrsz = get(0,'ScreenSize');
H.figwidth=850;
H.figheight=700;
H.stepwidth=300;
H.stepheight=30;
H.loadborder=10;
H.loadwidth=300;
H.loadheight=35;
H.vdecal=45;
%% STEP 1 : read all files
f0=figure('position',[(H.scrsz(3)-H.figwidth)/2,(H.scrsz(4)-H.figheight)/2,H.figwidth,H.figheight],...
    'name','GravProcess 1.3','NumberTitle','off');
filetext1=uicontrol('position',[(H.figwidth-H.stepwidth)/2 H.figheight-40 H.stepwidth H.stepheight],...
    'string','STEP 1 - INPUT FILES');
% lines
H.vpos=H.figheight-50-H.vdecal;
filetext2=uicontrol('visible','on','style','Text','position',[H.loadborder H.vpos H.loadwidth H.loadheight],...
    'string','Lines and calibration coefficient file ? (NoLINE COEFFICIENT)');
fileedit2=uicontrol('BackgroundColor',[1 1 1],'style','edit','position', ... 
 [2*H.loadborder+H.loadwidth H.vpos+5 H.figwidth-(3*H.loadborder+H.loadwidth) H.loadheight-10],...
 'string',strlines,'Callback','loadlines');
% gravity data
H.vpos=H.vpos-H.vdecal-35;
filetext3=uicontrol('visible',vallines,'style','Text','position',[H.loadborder H.vpos H.loadwidth 2*H.loadheight],...
    'string','Gravity data file (name after line number) ? (LINE STATION ALT GRAV GRAV_STD TILTX TILTY TEMPE TIDE DURATION REJECTED TIME DECIMAL_TIME TER DATE)');
fileedit3=uicontrol('visible',vallines,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [2*H.loadborder+H.loadwidth H.vpos+25 H.figwidth-(3*H.loadborder+H.loadwidth) H.loadheight-10],...
 'string',strdatagravi,'Callback','loadgravi');
% GPS file
H.vpos=H.vpos-H.vdecal;
filetext4=uicontrol('visible',valgravi,'style','Text','position',[H.loadborder H.vpos H.loadwidth H.loadheight],...
    'string','GPS location file ? (LON LAT ALT ALTITUDE_STD STATION)');
fileedit4=uicontrol('visible',valgravi,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [2*H.loadborder+H.loadwidth H.vpos+5 H.figwidth-(3*H.loadborder+H.loadwidth) H.loadheight-10],...
 'string',strGPSlocation,'Callback','loadGPS');
% Relative network adjustment
H.vpos=H.vpos-H.vdecal;
filetext5=uicontrol('visible',valGPS,'style','Text','position',[H.loadborder H.vpos H.loadwidth H.loadheight],...
    'string','Relative network adjustment file ? (LINE1 LINE2 LINE_attached(with respect to LINE2))');
fileedit5=uicontrol('visible',valGPS,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [2*H.loadborder+H.loadwidth H.vpos+5 H.figwidth-(3*H.loadborder+H.loadwidth) H.loadheight-10],...
 'string',strattachlist,'Callback','loadattach');
% Absolute network adjustment
H.vpos=H.vpos-H.vdecal;
filetext6=uicontrol('visible',valattach,'style','Text','position',[H.loadborder H.vpos H.loadwidth H.loadheight],...
    'string','Absolute network adjustment file ? (LON_BASE LAT_BASE GRAVITY_BASE)');
fileedit6=uicontrol('visible',valattach,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [2*H.loadborder+H.loadwidth H.vpos+5 H.figwidth-(3*H.loadborder+H.loadwidth) H.loadheight-10],...
 'string',strgravbase,'Callback','loadattachabs');
% DEM
H.vpos=H.vpos-H.vdecal;
filetext7=uicontrol('visible',valattachabs,'style','Text','position',[H.loadborder H.vpos H.loadwidth/2 H.loadheight],...
    'string','Complete Bouguer anomaly ?');
hpop1 = uicontrol('visible',valattachabs,'Style', 'popup',...
       'String', 'Yes|No','Value',valuehpop1,...
       'Position', [2*H.loadborder+H.loadwidth/2 H.vpos-20 40 50],...
       'Callback', 'completebouguer');
filetext7b=uicontrol('visible',valcomplete,'style','Text','position',[3*H.loadborder+H.loadwidth/2+40 H.vpos H.loadwidth/2 H.loadheight],...
    'string','DEM file ? (LON LAT ALTITUDE)');
fileedit7=uicontrol('visible',valcomplete,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [4*H.loadborder+H.loadwidth+40 H.vpos+5 H.loadwidth/2 H.loadheight-10],...
 'string',strDEM,'Callback','loadDEM');
filetext8=uicontrol('visible',valDEM,'style','Text','position',[5*H.loadborder+3*H.loadwidth/2+40 H.vpos H.loadwidth/2 H.loadheight],...
    'string','Mesh : Smin(km) dmax(km) alpha');
fileedit8=uicontrol('visible',valDEM,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [6*H.loadborder+2*H.loadwidth+40 H.vpos+5 H.figwidth-(7*H.loadborder+2*H.loadwidth+40) H.loadheight-10],...
 'string',strDEMparam,'Callback','meshparameter');
% Ocean tide
H.vpos=H.vpos-H.vdecal;
filetext9=uicontrol('visible',valmesh,'style','Text','position',[H.loadborder H.vpos H.loadwidth/2 H.loadheight],...
    'string','Ocean tide correction ?');
hpop2 = uicontrol('visible',valmesh,'Style', 'popup',...
       'String', 'Yes|No','Value',valuehpop2,...
       'Position', [2*H.loadborder+H.loadwidth/2 H.vpos-20 40 50],...
       'Callback', 'loadtidal');
filetext9b=uicontrol('visible',valtidal,'style','Text','position',[3*H.loadborder+H.loadwidth/2+40 H.vpos H.loadwidth/2+50 H.loadheight],...
    'string','Ocean loading file ? (from H.-G. Scherneck)');
fileedit9=uicontrol('visible',valtidal,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [4*H.loadborder+H.loadwidth+40+50 H.vpos+5 H.figwidth-(5*H.loadborder+H.loadwidth+40+50) H.loadheight-10],...
 'string',stroceantidal,'Callback','loadoceantide');
% Air pressure
H.vpos=H.vpos-H.vdecal;
filetext10=uicontrol('visible',valocean,'style','Text','position',[H.loadborder H.vpos H.loadwidth/2 H.loadheight],...
    'string','Pressure correction ?');
hpop3= uicontrol('visible',valocean,'Style', 'popup',...
       'String', 'Yes|No','Value',valuehpop3,...
       'Position', [2*H.loadborder+H.loadwidth/2 H.vpos-20 40 50],...
       'Callback', 'loadpressure');

filetext10b=uicontrol('visible',valpressure,'style','Text','position',[3*H.loadborder+H.loadwidth/2+40 H.vpos H.loadwidth/2+50 H.loadheight],...
    'string','Pressure file ? (STATION PRESSURE TIME DATE)');
fileedit10=uicontrol('visible',valpressure,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [4*H.loadborder+H.loadwidth+40+50 H.vpos+5 H.figwidth-(5*H.loadborder+H.loadwidth+40+50) H.loadheight-10],...
 'string',strpressure,'Callback','loadairpressure');
% Processing parameters
H.vpos=H.vpos-1.2*H.vdecal;
filetext11=uicontrol('visible',valair,'style','Text','position',[H.loadborder H.vpos H.loadwidth/2 H.loadheight],...
    'string','Parallel computing ?');
hpop4= uicontrol('visible',valair,'Style', 'popup',...
       'String', 'Yes|No','Value',valuehpop4,...
       'Position', [2*H.loadborder+H.loadwidth/2 H.vpos-20 40 50],...
       'Callback', 'parallelparameter');
filetext12=uicontrol('visible',valpara,'style','Text','position',[6*H.loadborder+H.loadwidth/2+40 H.vpos H.loadwidth/2 H.loadheight],...
    'string','Drift: Degree of the polynomial function ?');
fileedit12=uicontrol('visible',valpara,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [7*H.loadborder+H.loadwidth+40 H.vpos+5 30 H.loadheight-10],...
 'string',strdegree,'Callback','driftdegree');
filetext13=uicontrol('visible',valdriftdegree,'style','Text','position',[11*H.loadborder+H.loadwidth+70 H.vpos H.loadwidth/2 H.loadheight],...
    'string','Uncertainty in the DEM (m) ?');
fileedit13=uicontrol('visible',valdriftdegree,'BackgroundColor',[1 1 1],'style','edit','position', ... 
 [12*H.loadborder+3*H.loadwidth/2+70 H.vpos+5 30 H.loadheight-10],...
 'string',strDEMerror,'Callback','DEMerrorparameter');
%% STEP 2 : Processing
H.vpos=H.vpos-H.vdecal-5;
filetext14=uicontrol('visible',valDEMerror,'position',[(H.figwidth-H.stepwidth)/2 H.vpos H.stepwidth H.stepheight],...
    'string','STEP 2 - RUN GRAVITY DATA PROCESSING','Callback','runprocess');
filetext14b=uicontrol('visible',valrun,'ForegroundColor','red','style','Text','position',...
    [(H.figwidth-H.stepwidth)/2+H.stepwidth+H.loadborder H.vpos+5 H.stepwidth/2 H.loadheight/2],...
    'string','done','Callback','runprocess');
%% STEP 3 : Ouput
H.vpos=H.vpos-H.vdecal-5;
filetext15=uicontrol('visible',valrun,'position',[(H.figwidth-H.stepwidth)/2 H.vpos H.stepwidth H.stepheight],...
    'string','STEP 3 - OUTPUT');
%
%
H.vpos=H.vpos-H.vdecal;
scalartext1=uicontrol('visible',valrun,'style','Text','String','Plot results','Position',[H.loadborder H.vpos-10 150 H.stepheight]);
hpop5 = uicontrol('visible',valrun,'Style', 'popup',...
       'String', 'Instrumental drift|Network adjustment|Air pressure effect|Earth & Ocean Tide|Gravity field|Free air anomaly|Bouguer anomaly|Uncertainties|Close all figures',...
       'Value',valuehpop5,'Position', [H.loadborder H.vpos-70 150 50],...
       'Callback', 'plotresult');
%
filetext16=uicontrol('visible',valrun,'style','Text','position',[3*H.loadborder+150 H.vpos-20 H.figwidth-(4*H.loadborder+150) 1.6*H.stepheight],...
    'string','Output gravity data processing file ? (STATION LON LAT ALT GRAV GRAV_STD FREE-AIR FREE-AIR_STD BOUGUER BOUUGUER_STD DATA_STD DRIFT_STD NETWORK_ADJUST_STD ABS_STD ALT_STA_STD DEM_STD)');
fileedit16=uicontrol('visible',valrun,'BackgroundColor',[1 1 1],'style','edit','position',...
    [3*H.loadborder+150 H.vpos-20-30 H.figwidth-(4*H.loadborder+150) H.loadheight-10],'string',stroutfile,'Callback','saveoutput');
%% Refresh windows
indice=findall(0,'type','figure');
if (length(indice)>1)
    close(indice(2:length(indice)))
end;
